---
- hosts: web
  user: ubuntu
  gather_facts: no
  tasks:
  - name: configuration play
    vars:
      - ansible_python_interpreter: /usr/bin/python3
      - ansible_host_key_checking: false
      - ansible_stdout_callback: yaml
  - name: Wait 300 seconds, but only start checking after 60 seconds
    wait_for_connection:
    delay: 60
    timeout: 300
  
    roles:
    - configure-server