---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


- name: Unarchive backend files
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/
 
- name: "install dependencies and npm "
  become: true
  command: |
        sudo npm install -g n
        sudo n latest
        sudo npm install -g npm
        hash -d npm
        npm i
  args: 
    chdir: /home/ubuntu/backend
    
#- name: "install dependencies again"
#  become: yes
#  apt:
#    name: ["nodejs", "npm"]
#    state: latest
#    update_cache: yes
#    
#- name: "install NPM"
#  command: npm i
#  args: 
#    chdir: /home/ubuntu/backend
#    
#       
- name: "NPM Run Build"
  command: npm run build
  args: 
    chdir: /home/ubuntu/backend
    
- name: start pm2
  command: pm2 start npm --name backend -- start
  args: 
    chdir: /home/ubuntu/backend