---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


- name: Unarchive backend files
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/
    
- name: build node
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm install -g npm@latest
    npm audit fix --audit-level=critical --force
    npm run build
    
    
- name: Executing node
  become: yes
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start